FROM python:3.12-slim-bullseye

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Node.js 18.x とnpm、Tailwind CLIをインストール
RUN apt update && apt install -y \
    gcc \
    default-libmysqlclient-dev \
    pkg-config \
    curl \
    netcat \
    default-mysql-client \
    && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt install -y nodejs \
    && npm install -g npm@latest \
    && npm install -g tailwindcss \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

# ログディレクトリの設定
RUN mkdir -p /var/log/django && \
    chmod 777 /var/log/django

# 全てのファイルをコピー
COPY app .

# Python依存関係のインストール
RUN pip install --no-cache-dir -r requirements.txt

# Node.js依存関係のインストールとTailwindのビルド
RUN npm ci && npm run build:css

# 開発サーバー起動用のスクリプトをコピー
COPY docker/app/entrypoint.dev.sh /entrypoint.dev.sh
RUN chmod +x /entrypoint.dev.sh

# エントリーポイントとコマンドを設定
ENTRYPOINT ["/entrypoint.dev.sh"]
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]